// Package verifier walks a DNSSEC chain of trust from the root zone
// down to a requested (qname, qtype), classifies the result as one of
// Secure / Insecure / Bogus / Indeterminate, and surfaces the raw
// evidence (DS / DNSKEY / RRSIG records) used along the way.
//
// Architecture
//
// The chain walker is intentionally decoupled from any specific
// transport. A caller-supplied [Resolver] returns the records for a
// (name, qtype) tuple; the verifier reassembles them into per-zone
// [github.com/shigeya/dnsdata-go/dnssec.Zone] instances and reuses the
// signature-verification primitives from that package. As a result
// the same Verifier can be driven by DoH (resolver/doh), authoritative
// queries (resolver/auth, future), or any in-memory test fixture.
//
// Scope
//
// v0.1.0 ships positive validation: every zone on the path from root
// to qname has a usable DNSKEY rrset and the qname's RRset is signed
// by that zone's keys.
//
// v0.2.0 adds NSEC / NSEC3 negative proofs covering three cases:
//
// No-DS at delegation. When a parent returns no DS for a child name
// AND its response carries an NSEC/NSEC3 record that validly proves
// DS does not exist, the chain walker classifies that delegation as
// [VerdictInsecure] and records the proof source in
// [Result.InsecureReason]. Supported proof shapes:
//
//   - Matching NSEC with NS bit set, DS / SOA bits unset.
//   - Matching NSEC3 with the same bitmap shape.
//   - Covering NSEC3 with the opt-out flag set (RFC 5155 §6).
//
// NODATA at leaf. When the qname's rrset is empty but a matching
// NSEC/NSEC3 proves the qtype is missing (and CNAME is not present
// either), the verdict is [VerdictSecureNoData] with details in
// [Result.NegativeReason].
//
// NXDOMAIN at leaf. The strict RFC 4035 §5.4 / RFC 5155 §8.4
// closest-encloser proof: an NSEC/NSEC3 covers qname AND an NSEC/NSEC3
// covers the wildcard *.closest-encloser. NSEC3 NXDOMAIN further
// requires a separate next-closer covering NSEC3. Successful proof
// yields [VerdictSecureNXDomain].
//
// CNAME / DNAME chasing. The chain walker chases up to
// [MaxAliasHops] redirections. CNAMEs are followed when their RRSIG
// verifies under the zone they live in; DNAMEs at any proper
// ancestor of qname rewrite qname per RFC 6672 §5.3.1. Each hop is
// captured as an [AliasStep] in [Result.Aliases]. The terminal
// verdict is the worst-of across all hops: any Insecure hop yields
// Insecure, any Bogus hop yields Bogus, and so on. Repeated qnames
// in the chain are reported as Bogus with reason "alias loop
// detected"; chains longer than [MaxAliasHops] are reported as
// Bogus with reason "alias chain exceeded N hops".
//
// Out of scope (tracked separately):
//
//   - RFC 5011 trust-anchor key rollover.
//   - Caching of DNSKEY / DS rrsets across calls (the SHOULD #13 cache
//     hook in DESIGN.md §4 will land alongside the cache milestone).
//   - Wildcard-synthesised positive answers (the proof that a positive
//     answer was generated by wildcard expansion).
//
// Per the design rules in CLAUDE.md / DESIGN.md, the verifier holds no
// global mutable state and writes nothing to the filesystem / stdout
// / stderr by default. Multiple [Verifier] instances are independent
// and safe to use concurrently.
package verifier
